export const CHANGE_SAMPLE_RATE = "CHANGE_SAMPLE_RATE";

export const CHANGE_A_CONFIGURATION = "CHANGE_A_CONFIGURATION";
export const SAVING_CONFIGURATIONS = "SAVING_CONFIGURATIONS";
export const REQUEST_CONFIGURATIONS = "REQUEST_CONFIGURATIONS";
export const RECEIVE_CONFIGURATIONS = "RECEIVE_CONFIGURATIONS";

export const FETCH_APP_INFO = "FETCH_APP_INFO";
export const RECEIVE_APP_INFO = 'RECEIVE_APP_INFO';
export const REQUEST_APP_INFO = 'REQUEST_APP_INFO';
export const INVALIDATE_APP_INFO = 'INVALIDATE_APP_INFO';
